version: '3.3'

services:
  app:
    image: bigomics/omicsplayground:latest
    ports:
      - 3838
    networks:
      - traefik-public
    deploy:
      replicas: ${APP_REPLICAS}
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 4G
      restart_policy:
        condition: on-failure
#      placement:
#        max_replicas_per_node: 0
#        constraints:
#          - node.role==worker
      labels:
        - traefik.enable=true 
        - traefik.docker.network=traefik-public 
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.app-http.rule=Host(`${APP_DOMAIN}`) # port 80
        - traefik.http.routers.app-http.entrypoints=http
        - traefik.http.routers.app-http.middlewares=https-redirect        
        - traefik.http.routers.app-https.rule=Host(`${APP_DOMAIN}`)
        - traefik.http.routers.app-https.entrypoints=https
        - traefik.http.routers.app-https.tls.certresolver=le # use the Let's Encrypt
        - traefik.http.services.app-https.loadbalancer.server.port=3838 
        - traefik.http.services.app-https.loadbalancer.sticky.cookie=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - /data/pgx:/omicsplayground/data

networks:
  traefik-public:
    external: true
