IMAGE = bigomics/omicsplayground:latest

default: 
	@echo After the docker starts, go to http://localhost:3838
	docker run --rm -p 3838:3838 $(IMAGE)

pull:
	echo Pulling docker $(IMAGE)
	docker pull $(IMAGE)


